from transformers import AutoModelForCausalLM, AutoTokenizer
from data_access.chromadb_repo import get_similar_documents
from services.grok_service import call_grok
#from utils.translator import detect_and_translate, translate_to_language, map_langdetect_to_seamless
import torch
import gc


def rag_inference(user_input: str) -> str:
    """
    Perform RAG (Retrieval-Augmented Generation) inference using a pre-trained model.

    Args:
        user_input: The user's input.

    Returns:
        A response generated by the RAG model.
    """
    similar_documents = get_similar_documents(user_input, n=1)
    print(similar_documents)
    model_id = "microsoft/Phi-4-mini-instruct"
    tokenizer = AutoTokenizer.from_pretrained(model_id)

    conversation = [
        {"role": "system",
         "content": "You are a helpful AI assistant that provides groudned answers. Answer only based on the provided context. Be as precise as possible."
         },
        {"role": "user", "content": f'###CONTEXT{similar_documents}###QUESTION:{user_input}!@#$%'}
    ]

    inputs = tokenizer.apply_chat_template(
        conversation,
        add_generation_prompt=True,
        return_dict=True,
        return_tensors="pt",
    )

    model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.bfloat16, device_map="auto")
    inputs.to(model.device)
    outputs = model.generate(**inputs, max_new_tokens=1000)
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    del model
    gc.collect()
    torch.cuda.empty_cache()
    answer = answer.split("!@#$%")[-1].strip()

    return answer


def rag_inference_azure(user_input: str) -> str:
    """
    Perform RAG (Retrieval-Augmented Generation) inference using a pre-trained model.

    Args:
        user_input: The user's input.

    Returns:
        A response generated by the RAG model.
    """
    similar_documents_full = get_similar_documents(user_input, n=3)

    document_content = ""
    if 'documents' in similar_documents_full and similar_documents_full['documents']:

        document_content = "\n\n".join([doc for sublist in similar_documents_full['documents'] for doc in sublist])

    print(document_content)

    system_prompt = "You are a helpful AI assistant that provides grounded answers. Answer only based on the provided context. Be as precise as possible. Don't output thinking process, just the final answer, be as consice as possible and always answer in the same lagnauge the question is."
    user_prompt = f'###CONTEXT\n{document_content}\n###QUESTION:{user_input}'

    answer = call_grok(user_prompt, system_prompt)

    return answer


if __name__ == '__main__':
    print(rag_inference_azure("Ποιοι διδάσκουν τα μαθήματα εργαστηρίου του Αντικειμενοστρεφούς Προγραμματισμού;"))
